Repository VilledeMontreal/angular-ui, pull requests merged in 2022-03, with the labels that each got.

#33 fix: Update color for disabled element to tertiary color
  projects/angular-ui/src/lib/button/button.component.scss
  projects/angular-ui/src/lib/checkbox/checkbox.component.scss
  projects/angular-ui/src/lib/core/_colors.scss
  projects/angular-ui/src/lib/radio/radio.component.scss
  projects/angular-ui/src/lib/radio/radio.component.ts
Labels: enhancement

#40 fix: bao-icon display in safari
  projects/angular-ui/src/lib/alert/alert.component.scss
  projects/angular-ui/src/lib/icon/icon.component.scss
  projects/angular-ui/src/lib/tag/tag.component.scss
Labels: bug

#41 feat(alert): remove showIcon input to comply with accessibility rules.
  projects/angular-ui/src/lib/alert/alert.component.html
  projects/angular-ui/src/lib/alert/alert.component.ts
  projects/storybook-angular/src/stories/Alert/Alert.stories.ts
Labels: breaking changes :skull_and_crossbones:

#43 feat(alert): remove empty type and change default type. close #30.
  projects/angular-ui/src/lib/alert/alert.component.ts
  projects/storybook-angular/src/stories/Alert/Alert.stories.ts
Labels: breaking changes :skull_and_crossbones:

#57 feat(avatar): add bao-avatar component.
  projects/angular-ui/src/lib/avatar/avatar.component.html
  projects/angular-ui/src/lib/avatar/avatar.component.scss
  projects/angular-ui/src/lib/avatar/avatar.component.spec.ts
  projects/angular-ui/src/lib/avatar/avatar.component.ts
  projects/angular-ui/src/lib/avatar/index.ts
  projects/angular-ui/src/lib/avatar/module.ts
  projects/angular-ui/src/lib/avatar/tests/avatar.hostcomponent.spec.ts
  projects/angular-ui/src/lib/bao.module.ts
  projects/angular-ui/src/public-api.ts
  projects/storybook-angular/src/stories/Avatar/Avatar.stories.ts
Labels: new component 🎸
