Repository VilledeMontreal/angular-ui, pull requests merged in 2023-01, with the labels that each got.

#110 feat(file-input): add file-input component. close #88.
  projects/angular-ui/src/lib/bao.module.ts
  projects/angular-ui/src/lib/common-components/label-text/labelText.component.scss
  projects/angular-ui/src/lib/common-components/label-text/labelText.component.ts
  projects/angular-ui/src/lib/common-components/module.ts
  projects/angular-ui/src/lib/core/_typography.scss
  projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts
  projects/angular-ui/src/lib/file/file-input.component.html
  projects/angular-ui/src/lib/file/file-input.component.scss
  projects/angular-ui/src/lib/file/file-input.component.spec.ts
  projects/angular-ui/src/lib/file/file-input.component.ts
  projects/angular-ui/src/lib/file/file-intl.ts
  projects/angular-ui/src/lib/file/file-preview.component.html
  projects/angular-ui/src/lib/file/file-preview.component.scss
  projects/angular-ui/src/lib/file/file-preview.component.spec.ts
  projects/angular-ui/src/lib/file/file-preview.component.ts
  projects/angular-ui/src/lib/file/index.ts
  projects/angular-ui/src/lib/file/module.ts
  projects/angular-ui/src/lib/file/tests/file-input.hostcomponent.spec.ts
  projects/angular-ui/src/lib/file/tests/file-preview.hostcomponent.spec.ts
  projects/angular-ui/src/public-api.ts
  projects/storybook-angular-examples/src/app/file/file-example.component.html
  projects/storybook-angular-examples/src/app/file/file-example.component.ts
  projects/storybook-angular/src/stories/File/FileInput.stories.ts
  projects/storybook-angular/src/stories/File/FilePreview.stories.ts
Labels: new component 🎸

#109 feat(icon): #81 Add cell phone icon
  projects/angular-ui/src/lib/icon/icons-dictionary.ts
  projects/storybook-angular/src/stories/Icon/Icon.stories.ts
Labels: enhancement

#115 feat(file-input): add file-input component. close #88. (#110). For Angular 13
  projects/angular-ui/src/lib/bao.module.ts
  projects/angular-ui/src/lib/common-components/label-text/labelText.component.scss
  projects/angular-ui/src/lib/common-components/label-text/labelText.component.ts
  projects/angular-ui/src/lib/common-components/module.ts
  projects/angular-ui/src/lib/core/_typography.scss
  projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts
  projects/angular-ui/src/lib/file/file-input.component.html
  projects/angular-ui/src/lib/file/file-input.component.scss
  projects/angular-ui/src/lib/file/file-input.component.spec.ts
  projects/angular-ui/src/lib/file/file-input.component.ts
  projects/angular-ui/src/lib/file/file-intl.ts
  projects/angular-ui/src/lib/file/file-preview.component.html
  projects/angular-ui/src/lib/file/file-preview.component.scss
  projects/angular-ui/src/lib/file/file-preview.component.spec.ts
  projects/angular-ui/src/lib/file/file-preview.component.ts
  projects/angular-ui/src/lib/file/index.ts
  projects/angular-ui/src/lib/file/module.ts
  projects/angular-ui/src/lib/file/tests/file-input.hostcomponent.spec.ts
  projects/angular-ui/src/lib/file/tests/file-preview.hostcomponent.spec.ts
  projects/angular-ui/src/public-api.ts
  projects/storybook-angular-examples/src/app/file/file-example.component.html
  projects/storybook-angular-examples/src/app/file/file-example.component.ts
  projects/storybook-angular/src/stories/File/FileInput.stories.ts
  projects/storybook-angular/src/stories/File/FilePreview.stories.ts
Labels: enhancement

#118 fix(file): remove unnecessary margin and fix error when no guiding text is provided
  projects/angular-ui/src/lib/file/file-input.component.scss
  projects/angular-ui/src/lib/file/file-input.component.ts
  projects/angular-ui/src/lib/file/file-preview.component.scss
Labels: bug 🔥

#120 fix(file): remove unnecessary margin and fix error when no guiding test is provided. close #117.
  projects/angular-ui/src/lib/file/file-input.component.scss
  projects/angular-ui/src/lib/file/file-input.component.ts
  projects/angular-ui/src/lib/file/file-preview.component.scss
Labels: bug 🔥

#122 Feature/remove animation angular 14
  package-lock.json
  package.json
  projects/angular-ui/package-lock.json
  projects/angular-ui/package.json
  projects/angular-ui/src/lib/bao.module.ts
  projects/angular-ui/src/lib/modal/modal-container.ts
  projects/angular-ui/src/lib/modal/modal-ref.ts
  projects/angular-ui/src/lib/modal/modal.ts
  projects/angular-ui/src/lib/modal/module.ts
  projects/storybook-angular-examples/src/app/app.module.ts
Labels: bug 🔥

#125 fix(dropdown-menu): fix menu does not close when menu item is clicked
  projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.spec.ts
  projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts
  projects/angular-ui/src/lib/dropdown-menu/tests/dropdown-menu.hostcomponent.spec.ts
  projects/storybook-angular/src/stories/DropdownMenu/DropdownMenu.stories.ts
Labels: bug 🔥
